/**
 * GENERATED by scripts/harvest-headers.mjs — do not edit by hand.
 * H2/H3 section headers harvested from every lesson's MDX, each with the
 * github-slugger anchor rehype-slug emits. Feeds the concept linker's target
 * index (src/lib/graph/targets.ts): existing concepts gain section anchors, new
 * header concepts become global targets. Re-run: pnpm harvest-headers.
 */
export interface HeaderRecord {
  /** Owning lesson slug. */
  slug: string;
  /** github-slugger anchor id of the heading (matches the rendered DOM id). */
  anchor: string;
  /** The concept phrase to match (pre-subtitle, article-stripped). */
  phrase: string;
  /** The full cleaned heading text (for reference / tooltips). */
  text: string;
}

export const HEADER_RECORDS: HeaderRecord[] = [
  {
    "slug": "afine",
    "anchor": "the-image-quality-assessment-problem",
    "phrase": "image-quality assessment problem",
    "text": "The image-quality assessment problem"
  },
  {
    "slug": "afine",
    "anchor": "the-classical-baselines-and-why-they-arent-enough",
    "phrase": "classical baselines and why they aren't enough",
    "text": "The classical baselines and why they aren't enough"
  },
  {
    "slug": "afine",
    "anchor": "psnr--peak-signal-to-noise-ratio",
    "phrase": "PSNR",
    "text": "PSNR — Peak Signal-to-Noise Ratio"
  },
  {
    "slug": "afine",
    "anchor": "ssim--structural-similarity-index",
    "phrase": "SSIM",
    "text": "SSIM — Structural Similarity Index"
  },
  {
    "slug": "afine",
    "anchor": "watching-the-two-metrics-disagree",
    "phrase": "Watching the two metrics disagree",
    "text": "Watching the two metrics disagree"
  },
  {
    "slug": "afine",
    "anchor": "the-cnn-feature-family",
    "phrase": "CNN-feature family",
    "text": "The CNN-feature family"
  },
  {
    "slug": "afine",
    "anchor": "enter-a-fine--the-architecture",
    "phrase": "Enter A-FINE",
    "text": "Enter A-FINE — the architecture"
  },
  {
    "slug": "afine",
    "anchor": "the-naturalness-head",
    "phrase": "naturalness head",
    "text": "The naturalness head"
  },
  {
    "slug": "afine",
    "anchor": "the-fidelity-head--ssim-but-in-feature-space",
    "phrase": "fidelity head",
    "text": "The fidelity head — SSIM, but in feature space"
  },
  {
    "slug": "afine",
    "anchor": "the-logistic-calibrators",
    "phrase": "logistic calibrators",
    "text": "The logistic calibrators"
  },
  {
    "slug": "afine",
    "anchor": "goal-driven-exploration--five-parameter-logistic-calibrator",
    "phrase": "Goal-driven exploration",
    "text": "Goal-driven exploration — five-parameter logistic calibrator"
  },
  {
    "slug": "afine",
    "anchor": "the-adapter--where-adaptive-lives",
    "phrase": "adapter",
    "text": "The adapter — where \"adaptive\" lives"
  },
  {
    "slug": "afine",
    "anchor": "putting-it-together--one-concrete-walkthrough",
    "phrase": "Putting it together",
    "text": "Putting it together — one concrete walkthrough"
  },
  {
    "slug": "afine",
    "anchor": "what-a-fine-doesnt-do",
    "phrase": "What A-FINE doesn't do",
    "text": "What A-FINE doesn't do"
  },
  {
    "slug": "afine",
    "anchor": "three-implementation-traps-the-ones-that-catch-parity-tests",
    "phrase": "Three implementation traps (the ones that catch parity tests)",
    "text": "Three implementation traps (the ones that catch parity tests)"
  },
  {
    "slug": "afine",
    "anchor": "where-to-read-next",
    "phrase": "Where to read next",
    "text": "Where to read next"
  },
  {
    "slug": "linear-algebra-foundations",
    "anchor": "scalars--a-single-number-with-units",
    "phrase": "Scalars",
    "text": "Scalars — a single number, with units"
  },
  {
    "slug": "linear-algebra-foundations",
    "anchor": "vectors--a-list-of-components-geometrically-an-arrow",
    "phrase": "Vectors",
    "text": "Vectors — a list of components, geometrically an arrow"
  },
  {
    "slug": "linear-algebra-foundations",
    "anchor": "magnitude-ranker--your-eye-lies-about-length",
    "phrase": "Magnitude ranker",
    "text": "Magnitude ranker — your eye lies about length"
  },
  {
    "slug": "linear-algebra-foundations",
    "anchor": "component-reverse-engineer--read-the-arrow-back-into-numbers",
    "phrase": "Component reverse-engineer",
    "text": "Component reverse-engineer — read the arrow back into numbers"
  },
  {
    "slug": "linear-algebra-foundations",
    "anchor": "vector-addition--head-to-tail",
    "phrase": "Vector addition",
    "text": "Vector addition — head to tail"
  },
  {
    "slug": "linear-algebra-foundations",
    "anchor": "chain-construction--a-puzzle-for-the-head-to-tail-rule",
    "phrase": "Chain construction",
    "text": "Chain construction — a puzzle for the head-to-tail rule"
  },
  {
    "slug": "linear-algebra-foundations",
    "anchor": "walls-budgets-and-order--vector-addition-as-embodied-translation",
    "phrase": "Walls, budgets, and order",
    "text": "Walls, budgets, and order — vector addition as embodied translation"
  },
  {
    "slug": "linear-algebra-foundations",
    "anchor": "scalar-multiplication",
    "phrase": "Scalar multiplication",
    "text": "Scalar multiplication"
  },
  {
    "slug": "linear-algebra-foundations",
    "anchor": "speed-match--three-seconds-pick-the-scalar",
    "phrase": "Speed-match",
    "text": "Speed-match — three seconds, pick the scalar"
  },
  {
    "slug": "linear-algebra-foundations",
    "anchor": "the-dot-product--a-way-to-multiply-two-vectors-into-a-scalar",
    "phrase": "dot product",
    "text": "The dot product — a way to multiply two vectors into a scalar"
  },
  {
    "slug": "linear-algebra-foundations",
    "anchor": "whats-next",
    "phrase": "What's next",
    "text": "What's next"
  },
  {
    "slug": "linear-algebra-matrices",
    "anchor": "the-22-matrix",
    "phrase": "2×2 matrix",
    "text": "The 2×2 matrix"
  },
  {
    "slug": "linear-algebra-matrices",
    "anchor": "determinants--the-area-scaling-factor",
    "phrase": "Determinants",
    "text": "Determinants — the area-scaling factor"
  },
  {
    "slug": "linear-algebra-matrices",
    "anchor": "singularity-is-a-knife-edge",
    "phrase": "Singularity is a knife edge",
    "text": "Singularity is a knife edge"
  },
  {
    "slug": "linear-algebra-matrices",
    "anchor": "matrix-guessr--read-the-matrix-off-the-picture",
    "phrase": "Matrix Guessr",
    "text": "Matrix Guessr — read the matrix off the picture"
  },
  {
    "slug": "linear-algebra-matrices",
    "anchor": "the-named-transformation-dictionary",
    "phrase": "named-transformation dictionary",
    "text": "The named-transformation dictionary"
  },
  {
    "slug": "linear-algebra-matrices",
    "anchor": "spatial-prediction--where-will-the-corners-land",
    "phrase": "Spatial prediction",
    "text": "Spatial prediction — where will the corners land?"
  },
  {
    "slug": "linear-algebra-matrices",
    "anchor": "matrix-vector-multiplication--a-transformation-in-motion",
    "phrase": "Matrix-vector multiplication",
    "text": "Matrix-vector multiplication — a transformation in motion"
  },
  {
    "slug": "linear-algebra-matrices",
    "anchor": "composition-of-transformations-is-matrix-multiplication",
    "phrase": "Composition of transformations is matrix multiplication",
    "text": "Composition of transformations is matrix multiplication"
  },
  {
    "slug": "linear-algebra-matrices",
    "anchor": "speed-round--read-the-matrix-at-a-glance",
    "phrase": "Speed round",
    "text": "Speed round — read the matrix at a glance"
  },
  {
    "slug": "linear-algebra-matrices",
    "anchor": "where-to-read-next",
    "phrase": "Where to read next",
    "text": "Where to read next"
  },
  {
    "slug": "linear-algebra-dot-product",
    "anchor": "the-two-faces-of-the-dot-product",
    "phrase": "two faces of the dot product",
    "text": "The two faces of the dot product"
  },
  {
    "slug": "linear-algebra-dot-product",
    "anchor": "building-the-sum-one-product-at-a-time",
    "phrase": "Building the sum, one product at a time",
    "text": "Building the sum, one product at a time"
  },
  {
    "slug": "linear-algebra-dot-product",
    "anchor": "the-shadow-on-the-line",
    "phrase": "shadow on the line",
    "text": "The shadow on the line"
  },
  {
    "slug": "linear-algebra-dot-product",
    "anchor": "properties-worth-knowing",
    "phrase": "Properties worth knowing",
    "text": "Properties worth knowing"
  },
  {
    "slug": "linear-algebra-dot-product",
    "anchor": "aiming-for-a-right-angle",
    "phrase": "Aiming for a right angle",
    "text": "Aiming for a right angle"
  },
  {
    "slug": "linear-algebra-dot-product",
    "anchor": "the-dot-product-is-a-many-to-one-invariant",
    "phrase": "dot product is a many-to-one invariant",
    "text": "The dot product is a many-to-one invariant"
  },
  {
    "slug": "linear-algebra-dot-product",
    "anchor": "magnitudes-and-angles-from-dot-products",
    "phrase": "Magnitudes and angles from dot products",
    "text": "Magnitudes and angles from dot products"
  },
  {
    "slug": "linear-algebra-dot-product",
    "anchor": "cosine-similarity-as-nearest-neighbour-search",
    "phrase": "Cosine similarity as nearest-neighbour search",
    "text": "Cosine similarity as nearest-neighbour search"
  },
  {
    "slug": "linear-algebra-dot-product",
    "anchor": "projection--the-operation-not-just-the-geometry",
    "phrase": "Projection",
    "text": "Projection — the operation, not just the geometry"
  },
  {
    "slug": "linear-algebra-dot-product",
    "anchor": "predict-where-the-foot-lands",
    "phrase": "Predict where the foot lands",
    "text": "Predict where the foot lands"
  },
  {
    "slug": "linear-algebra-dot-product",
    "anchor": "a-worked-angle-calculation",
    "phrase": "worked angle calculation",
    "text": "A worked angle calculation"
  },
  {
    "slug": "linear-algebra-dot-product",
    "anchor": "where-to-read-next",
    "phrase": "Where to read next",
    "text": "Where to read next"
  },
  {
    "slug": "linear-algebra-span",
    "anchor": "the-linear-combination",
    "phrase": "linear combination",
    "text": "The linear combination"
  },
  {
    "slug": "linear-algebra-span",
    "anchor": "linear-independence",
    "phrase": "Linear independence",
    "text": "Linear independence"
  },
  {
    "slug": "linear-algebra-span",
    "anchor": "find-every-dependent-pair--recognition-as-a-skill",
    "phrase": "Find every dependent pair",
    "text": "Find every dependent pair — recognition as a skill"
  },
  {
    "slug": "linear-algebra-span",
    "anchor": "click-to-test--span-as-something-you-interrogate-not-just-look-at",
    "phrase": "Click to test",
    "text": "Click to test — span as something you interrogate, not just look at"
  },
  {
    "slug": "linear-algebra-span",
    "anchor": "land-on-a-target--span-as-something-you-steer",
    "phrase": "Land on a target",
    "text": "Land on a target — span as something you steer"
  },
  {
    "slug": "linear-algebra-span",
    "anchor": "span-beyond-two-vectors",
    "phrase": "Span beyond two vectors",
    "text": "Span beyond two vectors"
  },
  {
    "slug": "linear-algebra-span",
    "anchor": "redundancy-as-a-puzzle",
    "phrase": "Redundancy as a puzzle",
    "text": "Redundancy as a puzzle"
  },
  {
    "slug": "linear-algebra-span",
    "anchor": "span-and-the-columns-of-a-matrix",
    "phrase": "Span and the columns of a matrix",
    "text": "Span and the columns of a matrix"
  },
  {
    "slug": "linear-algebra-span",
    "anchor": "build-the-reflex--basis-or-not-at-speed",
    "phrase": "Build the reflex",
    "text": "Build the reflex — basis or not, at speed"
  },
  {
    "slug": "linear-algebra-span",
    "anchor": "where-to-read-next",
    "phrase": "Where to read next",
    "text": "Where to read next"
  },
  {
    "slug": "linear-algebra-matrix-operations",
    "anchor": "the-easy-three--addition-scalar-multiplication-transpose",
    "phrase": "easy three",
    "text": "The easy three — addition, scalar multiplication, transpose"
  },
  {
    "slug": "linear-algebra-matrix-operations",
    "anchor": "matrix-multiplication--the-operation-where-everything-happens",
    "phrase": "Matrix multiplication",
    "text": "Matrix multiplication — the operation where everything happens"
  },
  {
    "slug": "linear-algebra-matrix-operations",
    "anchor": "ab-is-not-ba--the-most-important-non-commutativity-in-elementary-math",
    "phrase": "AB is not BA",
    "text": "AB is not BA — the most important non-commutativity in elementary math"
  },
  {
    "slug": "linear-algebra-matrix-operations",
    "anchor": "sixteen-judgements--when-does-ab-equal-ba",
    "phrase": "Sixteen judgements",
    "text": "Sixteen judgements — when does AB equal BA?"
  },
  {
    "slug": "linear-algebra-matrix-operations",
    "anchor": "how-big-is-the-gap--predicting-one-entry-at-a-time",
    "phrase": "How big is the gap?",
    "text": "How big is the gap? — predicting one entry at a time"
  },
  {
    "slug": "linear-algebra-matrix-operations",
    "anchor": "ordering-puzzle--non-commutativity-in-your-hands",
    "phrase": "Ordering puzzle",
    "text": "Ordering puzzle — non-commutativity in your hands"
  },
  {
    "slug": "linear-algebra-matrix-operations",
    "anchor": "two-facts-about-matrix-multiplication-that-do-hold",
    "phrase": "Two facts about matrix multiplication that DO hold",
    "text": "Two facts about matrix multiplication that DO hold"
  },
  {
    "slug": "linear-algebra-matrix-operations",
    "anchor": "matrix-vector-multiplication-revisited",
    "phrase": "Matrix-vector multiplication, revisited",
    "text": "Matrix-vector multiplication, revisited"
  },
  {
    "slug": "linear-algebra-matrix-operations",
    "anchor": "identity-inverse-and-what-comes-next",
    "phrase": "Identity, inverse, and what comes next",
    "text": "Identity, inverse, and what comes next"
  },
  {
    "slug": "linear-algebra-matrix-operations",
    "anchor": "where-to-read-next",
    "phrase": "Where to read next",
    "text": "Where to read next"
  },
  {
    "slug": "linear-algebra-matrix-inverse",
    "anchor": "the-undo-operation--what-an-inverse-is",
    "phrase": "undo operation",
    "text": "The undo operation — what an inverse is"
  },
  {
    "slug": "linear-algebra-matrix-inverse",
    "anchor": "when-inversion-fails--singular-matrices",
    "phrase": "When inversion fails",
    "text": "When inversion fails — singular matrices"
  },
  {
    "slug": "linear-algebra-matrix-inverse",
    "anchor": "the-closed-form-inverse",
    "phrase": "closed-form inverse",
    "text": "The closed-form inverse"
  },
  {
    "slug": "linear-algebra-matrix-inverse",
    "anchor": "three-lenses-on",
    "phrase": "Three lenses on",
    "text": "Three lenses on"
  },
  {
    "slug": "linear-algebra-matrix-inverse",
    "anchor": "gaussian-elimination--the-algorithm-that-does-everything",
    "phrase": "Gaussian elimination",
    "text": "Gaussian elimination — the algorithm that does everything"
  },
  {
    "slug": "linear-algebra-matrix-inverse",
    "anchor": "computing-by-row-reduction--the-trick",
    "phrase": "Computing by row reduction",
    "text": "Computing by row reduction — the trick"
  },
  {
    "slug": "linear-algebra-matrix-inverse",
    "anchor": "misconceptions",
    "phrase": "Misconceptions",
    "text": "Misconceptions"
  },
  {
    "slug": "linear-algebra-matrix-inverse",
    "anchor": "triage--read-the-signature-dont-solve",
    "phrase": "Triage",
    "text": "Triage — read the signature, don't solve"
  },
  {
    "slug": "linear-algebra-matrix-inverse",
    "anchor": "what-inversion-does-for-you-elsewhere-in-mathematics",
    "phrase": "What inversion does for you elsewhere in mathematics",
    "text": "What inversion does for you elsewhere in mathematics"
  },
  {
    "slug": "linear-algebra-matrix-inverse",
    "anchor": "where-to-read-next",
    "phrase": "Where to read next",
    "text": "Where to read next"
  },
  {
    "slug": "linear-algebra-basis",
    "anchor": "what-a-basis-is",
    "phrase": "What a basis is",
    "text": "What a basis is"
  },
  {
    "slug": "linear-algebra-basis",
    "anchor": "computing-coordinates-in-a-basis--the-inverse-strikes",
    "phrase": "Computing coordinates in a basis",
    "text": "Computing coordinates in a basis — the inverse strikes"
  },
  {
    "slug": "linear-algebra-basis",
    "anchor": "change-of-basis-as-a-transformation",
    "phrase": "Change of basis as a transformation",
    "text": "Change of basis as a transformation"
  },
  {
    "slug": "linear-algebra-basis",
    "anchor": "why-non-standard-bases-matter",
    "phrase": "Why non-standard bases matter",
    "text": "Why non-standard bases matter"
  },
  {
    "slug": "linear-algebra-basis",
    "anchor": "misconceptions",
    "phrase": "Misconceptions",
    "text": "Misconceptions"
  },
  {
    "slug": "linear-algebra-basis",
    "anchor": "the-general-definition--bases-in-and-beyond",
    "phrase": "general definition",
    "text": "The general definition — bases in and beyond"
  },
  {
    "slug": "linear-algebra-basis",
    "anchor": "where-to-read-next",
    "phrase": "Where to read next",
    "text": "Where to read next"
  }
];
