/**
 * CoordinateTranslator — basis-swap navigation puzzle.
 *
 * Used by:
 *   - linear-algebra-basis (this lesson)
 * Cross-link candidates:
 *   - linear-algebra-foundations (vectors and components)
 *   - linear-algebra-span (the lattice generated by integer α·u + β·v)
 *   - any future eigenvectors lesson (eigenbases are also "controls in
 *     the new basis", just with diagonal action)
 *
 * THIS IS A NAVIGATION GAME. Not a slider, not a chart — a ship sits at
 * the origin on a grid drawn in the standard basis. A target point T is
 * displayed in the plane (you can see it standing in standard-basis
 * space), but the *only label* given for T is its CUSTOM-BASIS
 * coordinates (α, β). The reader's controls (+u / -u / +v / -v buttons,
 * or arrow keys) move the ship by one step IN THE CUSTOM BASIS. Pressing
 * "+u" translates the ship by +u in standard-basis space; pressing "+v"
 * translates by +v. The reader must mentally compose the moves so that
 * (number of +u presses) - (number of -u presses) equals α and
 * (number of +v presses) - (number of -v presses) equals β.
 *
 * The pedagogical insight: in the custom basis, the target's coordinates
 * are (α, β), and reaching it from the origin requires exactly α u-moves
 * and β v-moves. The reader is *executing* the change-of-basis identity
 *   T = α·u + β·v
 * with their fingers. The widget refuses to give them the standard-basis
 * coordinates until they ask (the "show standard coords" toggle) — the
 * point of the exercise is to navigate using the custom-basis controls
 * as the *primary* reading of where the target lives.
 *
 * Win-state: ship within ε of target. Score = moves used; minimum moves
 * = |α| + |β|.
 *
 * Implements metaphor library §8 (physical metaphor — a ship under
 * basis-controlled thrust) + a brand-new "controls in another basis"
 * mechanic that no Tessarix widget has had before. Foreshadows the
 * eigenbasis-as-natural-controls intuition the eigenvectors lesson will
 * need.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { resolveColor, resolveColorAlpha } from "../../../lib/theme";
import { computeDomain, makeToPx } from "../../../lib/geometry";
import { useWidgetTelemetry } from "../../../lib/telemetry";
import { WidgetExplainer } from "../shared/WidgetExplainer";
import "./CoordinateTranslator.css";

const CANVAS_SIZE = 360;
const SUCCESS_EPS = 0.18;

interface Vec2 {
  x: number;
  y: number;
}

interface Puzzle {
  label: string;
  u: Vec2;
  v: Vec2;
  /** Target's coordinates in the CUSTOM basis {u, v}. The standard-basis
   * position is computed at runtime as α·u + β·v. */
  alpha: number;
  beta: number;
  /** Friendly description for the explainer. */
  description: string;
}

const PUZZLES: Puzzle[] = [
  {
    label: "Rotated 30°",
    u: { x: 0.866, y: 0.5 },
    v: { x: -0.5, y: 0.866 },
    alpha: 2,
    beta: 1,
    description:
      "Basis tilted 30° counter-clockwise from the standard axes — u points up-and-right, v points up-and-left.",
  },
  {
    label: "Stretched diagonal",
    u: { x: 1.5, y: 1.5 },
    v: { x: -1, y: 1 },
    alpha: 1,
    beta: 2,
    description:
      "Diagonal basis. u points up-right with length √(4.5); v points up-left. Most of the target's reach is in v-presses.",
  },
  {
    label: "Sheared right",
    u: { x: 1, y: 0 },
    v: { x: 0.8, y: 1 },
    alpha: -1,
    beta: 3,
    description:
      "Sheared basis. u still points right but v is tilted — pressing +v moves the ship up AND slightly right.",
  },
  {
    label: "Negative target",
    u: { x: 1.2, y: 0.4 },
    v: { x: -0.4, y: 1.3 },
    alpha: -2,
    beta: -1,
    description:
      "Target sits in the third quadrant. You need negative coordinates in both u and v.",
  },
];

interface CoordinateTranslatorProps {
  onStateChange?: (state: Record<string, number>) => void;
}

export function CoordinateTranslator({
  onStateChange,
}: CoordinateTranslatorProps) {
  const { recordInteraction } = useWidgetTelemetry("CoordinateTranslator");
  const [puzzleIdx, setPuzzleIdx] = useState(0);
  // Ship's coordinates IN THE CUSTOM BASIS — integer counts of +u, +v moves.
  const [shipA, setShipA] = useState(0);
  const [shipB, setShipB] = useState(0);
  const [moves, setMoves] = useState(0);
  const [showStandard, setShowStandard] = useState(false);

  const puzzle = PUZZLES[puzzleIdx];

  // Ship's position in STANDARD basis = shipA·u + shipB·v.
  const shipStd = useMemo(
    () => ({
      x: shipA * puzzle.u.x + shipB * puzzle.v.x,
      y: shipA * puzzle.u.y + shipB * puzzle.v.y,
    }),
    [shipA, shipB, puzzle],
  );

  // Target's position in STANDARD basis = α·u + β·v.
  const targetStd = useMemo(
    () => ({
      x: puzzle.alpha * puzzle.u.x + puzzle.beta * puzzle.v.x,
      y: puzzle.alpha * puzzle.u.y + puzzle.beta * puzzle.v.y,
    }),
    [puzzle],
  );

  const distance = Math.hypot(
    shipStd.x - targetStd.x,
    shipStd.y - targetStd.y,
  );
  const isSolved = distance < SUCCESS_EPS;
  const minMoves = Math.abs(puzzle.alpha) + Math.abs(puzzle.beta);
  const isOptimal = isSolved && moves <= minMoves;

  useEffect(() => {
    if (!onStateChange) return;
    onStateChange({
      puzzle_index: puzzleIdx,
      ship_alpha: shipA,
      ship_beta: shipB,
      ship_std_x: Number(shipStd.x.toFixed(3)),
      ship_std_y: Number(shipStd.y.toFixed(3)),
      target_alpha: puzzle.alpha,
      target_beta: puzzle.beta,
      target_std_x: Number(targetStd.x.toFixed(3)),
      target_std_y: Number(targetStd.y.toFixed(3)),
      distance: Number(distance.toFixed(3)),
      moves,
      min_moves: minMoves,
      solved: isSolved ? 1 : 0,
      optimal: isOptimal ? 1 : 0,
      show_standard: showStandard ? 1 : 0,
    });
  }, [
    puzzleIdx,
    shipA,
    shipB,
    shipStd,
    targetStd,
    puzzle,
    distance,
    moves,
    minMoves,
    isSolved,
    isOptimal,
    showStandard,
    onStateChange,
  ]);

  const move = useCallback(
    (axis: "u" | "v", dir: 1 | -1) => {
      if (isSolved) return;
      if (axis === "u") setShipA((a) => a + dir);
      else setShipB((b) => b + dir);
      setMoves((m) => m + 1);
      recordInteraction("move", {
        axis,
        direction: dir,
      });
    },
    [isSolved, recordInteraction],
  );

  const reset = useCallback(() => {
    setShipA(0);
    setShipB(0);
    setMoves(0);
    recordInteraction("reset");
  }, [recordInteraction]);

  const nextPuzzle = useCallback(
    (idx: number) => {
      setPuzzleIdx(idx);
      setShipA(0);
      setShipB(0);
      setMoves(0);
      setShowStandard(false);
      recordInteraction("puzzle", { puzzle: PUZZLES[idx].label });
    },
    [recordInteraction],
  );

  // Keyboard navigation — focus on the canvas-wrap div listens for arrows.
  const wrapRef = useRef<HTMLDivElement | null>(null);
  useEffect(() => {
    const node = wrapRef.current;
    if (!node) return;
    const onKey = (e: KeyboardEvent) => {
      if (document.activeElement && (document.activeElement as HTMLElement).tagName === "INPUT")
        return;
      if (e.key === "ArrowUp" || e.key === "w" || e.key === "W") {
        e.preventDefault();
        move("v", 1);
      } else if (e.key === "ArrowDown" || e.key === "s" || e.key === "S") {
        e.preventDefault();
        move("v", -1);
      } else if (e.key === "ArrowRight" || e.key === "d" || e.key === "D") {
        e.preventDefault();
        move("u", 1);
      } else if (e.key === "ArrowLeft" || e.key === "a" || e.key === "A") {
        e.preventDefault();
        move("u", -1);
      } else if (e.key === "r" || e.key === "R") {
        e.preventDefault();
        reset();
      }
    };
    node.addEventListener("keydown", onKey);
    return () => node.removeEventListener("keydown", onKey);
  }, [move, reset]);

  const stateSummary = useMemo(() => {
    const customCoords = `ship at (α=${shipA}, β=${shipB}) in the custom basis`;
    const targetCoords = `target at (α=${puzzle.alpha}, β=${puzzle.beta}) in the custom basis`;
    const standard = `ship std-coords = (${shipStd.x.toFixed(2)}, ${shipStd.y.toFixed(2)}); target std-coords = (${targetStd.x.toFixed(2)}, ${targetStd.y.toFixed(2)})`;
    const status = isSolved
      ? isOptimal
        ? `SOLVED in ${moves} moves — optimal (min ${minMoves}).`
        : `Solved in ${moves} moves (min ${minMoves}). Try again from scratch and find the shorter path?`
      : `Working — distance ${distance.toFixed(2)}; ${moves} moves used so far.`;
    return `Puzzle "${puzzle.label}": ${customCoords}; ${targetCoords}. ${standard}. ${status}`;
  }, [
    puzzle,
    shipA,
    shipB,
    shipStd,
    targetStd,
    moves,
    minMoves,
    distance,
    isSolved,
    isOptimal,
  ]);

  const stateKey = useMemo(
    () =>
      JSON.stringify({
        puzzle: puzzleIdx,
        ship: [shipA, shipB],
        solved: isSolved,
      }),
    [puzzleIdx, shipA, shipB, isSolved],
  );

  return (
    <div
      className={`ct${isSolved ? " ct--solved" : ""}`}
      ref={wrapRef}
      tabIndex={0}
    >
      <header className="ct__head">
        <div className="ct__heading">
          <span className="ct__heading-label">PUZZLE</span>
          <span className="ct__heading-value">{puzzle.label}</span>
        </div>
        <div className="ct__heading">
          <span className="ct__heading-label">TARGET (CUSTOM)</span>
          <span className="ct__heading-value">
            (α, β) = ({puzzle.alpha}, {puzzle.beta})
          </span>
        </div>
        <div className="ct__heading">
          <span className="ct__heading-label">SHIP (CUSTOM)</span>
          <span className="ct__heading-value">
            (α, β) = ({shipA}, {shipB})
          </span>
        </div>
        <div className="ct__heading">
          <span className="ct__heading-label">MOVES</span>
          <span className="ct__heading-value">
            {moves} {minMoves > 0 && `· min ${minMoves}`}
          </span>
        </div>
      </header>

      <TranslatorCanvas
        puzzle={puzzle}
        shipStd={shipStd}
        targetStd={targetStd}
        isSolved={isSolved}
        showStandard={showStandard}
      />

      <div className="ct__pad">
        <span className="ct__pad-label">CONTROLS — these move you in the custom basis</span>
        <div className="ct__pad-grid">
          <div className="ct__pad-row">
            <button
              type="button"
              className="ct__pad-btn ct__pad-btn--v-up"
              onClick={() => move("v", 1)}
              disabled={isSolved}
            >
              <span className="ct__pad-axis">+v</span>
              <span className="ct__pad-hint">↑ / W</span>
            </button>
          </div>
          <div className="ct__pad-row">
            <button
              type="button"
              className="ct__pad-btn ct__pad-btn--u-down"
              onClick={() => move("u", -1)}
              disabled={isSolved}
            >
              <span className="ct__pad-axis">−u</span>
              <span className="ct__pad-hint">← / A</span>
            </button>
            <button
              type="button"
              className="ct__pad-btn ct__pad-btn--reset"
              onClick={reset}
            >
              <span className="ct__pad-axis">reset</span>
              <span className="ct__pad-hint">R</span>
            </button>
            <button
              type="button"
              className="ct__pad-btn ct__pad-btn--u-up"
              onClick={() => move("u", 1)}
              disabled={isSolved}
            >
              <span className="ct__pad-axis">+u</span>
              <span className="ct__pad-hint">→ / D</span>
            </button>
          </div>
          <div className="ct__pad-row">
            <button
              type="button"
              className="ct__pad-btn ct__pad-btn--v-down"
              onClick={() => move("v", -1)}
              disabled={isSolved}
            >
              <span className="ct__pad-axis">−v</span>
              <span className="ct__pad-hint">↓ / S</span>
            </button>
          </div>
        </div>
      </div>

      <div
        className={`ct__verdict ct__verdict--${
          isSolved ? (isOptimal ? "optimal" : "solved") : "working"
        }`}
      >
        <span className="ct__verdict-label">Status</span>
        <span className="ct__verdict-value">
          {isSolved
            ? isOptimal
              ? `✓ Reached the target in ${moves} moves — optimal.`
              : `✓ Reached the target in ${moves} moves. Minimum is ${minMoves} — reset and try the direct path.`
            : `Ship is ${distance.toFixed(2)} units from the target. Translate (${puzzle.alpha}, ${puzzle.beta}) custom-basis coordinates into u-and-v presses.`}
        </span>
      </div>

      <div className="ct__row">
        <button
          type="button"
          className={`ct__reveal${showStandard ? " ct__reveal--on" : ""}`}
          onClick={() => {
            setShowStandard((s) => !s);
            recordInteraction("toggle_standard", { on: !showStandard });
          }}
        >
          {showStandard ? "Hide standard coords" : "Show standard coords"}
        </button>
        <div className="ct__puzzle-row">
          {PUZZLES.map((p, i) => (
            <button
              key={p.label}
              type="button"
              className={`ct__puzzle-pick${i === puzzleIdx ? " ct__puzzle-pick--active" : ""}`}
              onClick={() => nextPuzzle(i)}
            >
              {p.label}
            </button>
          ))}
        </div>
      </div>

      <WidgetExplainer
        widgetName="Coordinate translator — navigate under a custom basis"
        widgetDescription="A navigation puzzle that forces the reader to enact the change-of-basis identity T = α·u + β·v with their fingers. A ship begins at the origin; a target is shown on a grid drawn in the standard basis. The target's only label is its CUSTOM-basis coordinates (α, β) — the standard-basis coordinates are hidden by default. The reader presses +u / -u / +v / -v (or arrow keys); each press translates the ship by ±u or ±v in standard-basis space. To reach the target the reader must compose α u-moves and β v-moves (counting signs). The widget tracks moves used vs the optimal |α| + |β|, and surfaces 'show standard coords' as an optional reveal for readers who want to double-check. The pedagogical point: under a custom basis, the controls and the target coordinates are in different languages from the rendering, and translating between them is the change-of-basis operation."
        stateSummary={stateSummary}
        stateKey={stateKey}
      />
    </div>
  );
}

// ─── Canvas ────────────────────────────────────────────────────────────

interface TranslatorCanvasProps {
  puzzle: Puzzle;
  shipStd: Vec2;
  targetStd: Vec2;
  isSolved: boolean;
  showStandard: boolean;
}

function TranslatorCanvas({
  puzzle,
  shipStd,
  targetStd,
  isSolved,
  showStandard,
}: TranslatorCanvasProps) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);

  const domain = useMemo(() => {
    return computeDomain(
      [
        puzzle.u,
        puzzle.v,
        targetStd,
        shipStd,
        { x: puzzle.u.x * 3, y: puzzle.u.y * 3 },
        { x: puzzle.v.x * 3, y: puzzle.v.y * 3 },
      ],
      { padding: 1.4, floor: 3, ceiling: 8 },
    );
  }, [puzzle, shipStd, targetStd]);

  const toPx = useMemo(() => makeToPx(CANVAS_SIZE, domain), [domain]);

  const draw = useCallback(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    const W = CANVAS_SIZE;
    const H = CANVAS_SIZE;
    ctx.clearRect(0, 0, W, H);

    const C_U = resolveColor("var(--widget-chart-1)");
    const C_V = resolveColor("var(--widget-chart-2)");
    const C_TARGET = resolveColor("var(--widget-chart-3)");
    const C_SHIP = isSolved
      ? resolveColor("var(--widget-success)")
      : resolveColor("var(--widget-accent)");
    const C_TEXT = resolveColor("var(--widget-text)");

    // Standard grid (faint).
    ctx.strokeStyle = "rgba(255, 255, 255, 0.05)";
    ctx.lineWidth = 1;
    const pxPerUnit = W / (2 * domain);
    const unitsPerHalf = Math.ceil(domain);
    for (let i = -unitsPerHalf; i <= unitsPerHalf; i++) {
      const xPx = W / 2 + i * pxPerUnit;
      const yPx = H / 2 - i * pxPerUnit;
      ctx.beginPath();
      ctx.moveTo(xPx, 0);
      ctx.lineTo(xPx, H);
      ctx.stroke();
      ctx.beginPath();
      ctx.moveTo(0, yPx);
      ctx.lineTo(W, yPx);
      ctx.stroke();
    }
    // Standard axes.
    ctx.strokeStyle = "rgba(255, 255, 255, 0.25)";
    ctx.lineWidth = 1.2;
    ctx.beginPath();
    ctx.moveTo(0, H / 2);
    ctx.lineTo(W, H / 2);
    ctx.moveTo(W / 2, 0);
    ctx.lineTo(W / 2, H);
    ctx.stroke();

    // Custom-basis grid — draw the lattice of integer u, v combinations.
    ctx.strokeStyle = resolveColorAlpha("var(--widget-chart-1)", 0.12);
    ctx.lineWidth = 1;
    const span = 5;
    for (let i = -span; i <= span; i++) {
      // u-aligned lines: each line goes through i·v in the v-direction along u.
      const s = toPx({
        x: -span * puzzle.u.x + i * puzzle.v.x,
        y: -span * puzzle.u.y + i * puzzle.v.y,
      });
      const e = toPx({
        x: span * puzzle.u.x + i * puzzle.v.x,
        y: span * puzzle.u.y + i * puzzle.v.y,
      });
      ctx.beginPath();
      ctx.moveTo(s.x, s.y);
      ctx.lineTo(e.x, e.y);
      ctx.stroke();
    }
    ctx.strokeStyle = resolveColorAlpha("var(--widget-chart-2)", 0.12);
    for (let i = -span; i <= span; i++) {
      const s = toPx({
        x: -span * puzzle.v.x + i * puzzle.u.x,
        y: -span * puzzle.v.y + i * puzzle.u.y,
      });
      const e = toPx({
        x: span * puzzle.v.x + i * puzzle.u.x,
        y: span * puzzle.v.y + i * puzzle.u.y,
      });
      ctx.beginPath();
      ctx.moveTo(s.x, s.y);
      ctx.lineTo(e.x, e.y);
      ctx.stroke();
    }

    // Basis arrows.
    const origin = toPx({ x: 0, y: 0 });
    drawArrow(ctx, origin, toPx(puzzle.u), C_U, "u", 2.4, false);
    drawArrow(ctx, origin, toPx(puzzle.v), C_V, "v", 2.4, false);

    // Target.
    const targetPx = toPx(targetStd);
    ctx.fillStyle = resolveColorAlpha("var(--widget-chart-3)", 0.16);
    ctx.beginPath();
    ctx.arc(targetPx.x, targetPx.y, 18, 0, Math.PI * 2);
    ctx.fill();
    ctx.strokeStyle = C_TARGET;
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.arc(targetPx.x, targetPx.y, 11, 0, Math.PI * 2);
    ctx.stroke();
    ctx.beginPath();
    ctx.arc(targetPx.x, targetPx.y, 4, 0, Math.PI * 2);
    ctx.fillStyle = C_TARGET;
    ctx.fill();
    ctx.font = "600 12px 'JetBrains Mono', ui-monospace, monospace";
    ctx.fillStyle = C_TARGET;
    const tlabel = showStandard
      ? `T = (${targetStd.x.toFixed(2)}, ${targetStd.y.toFixed(2)})_std`
      : `T = (${puzzle.alpha}, ${puzzle.beta})_{u,v}`;
    ctx.fillText(tlabel, targetPx.x + 14, targetPx.y - 12);

    // Ship.
    const shipPx = toPx(shipStd);
    // Path from origin to ship (dotted).
    ctx.strokeStyle = resolveColorAlpha("var(--widget-accent)", 0.42);
    ctx.lineWidth = 1.4;
    ctx.setLineDash([4, 4]);
    ctx.beginPath();
    ctx.moveTo(origin.x, origin.y);
    ctx.lineTo(shipPx.x, shipPx.y);
    ctx.stroke();
    ctx.setLineDash([]);

    // Ship glyph: a triangle.
    ctx.fillStyle = C_SHIP;
    ctx.strokeStyle = C_SHIP;
    ctx.lineWidth = 2;
    ctx.beginPath();
    ctx.arc(shipPx.x, shipPx.y, 7, 0, Math.PI * 2);
    ctx.fill();
    if (isSolved) {
      // Glow ring.
      ctx.strokeStyle = resolveColorAlpha("var(--widget-success)", 0.55);
      ctx.lineWidth = 3;
      ctx.beginPath();
      ctx.arc(shipPx.x, shipPx.y, 16, 0, Math.PI * 2);
      ctx.stroke();
    }

    // Label.
    ctx.fillStyle = C_SHIP;
    ctx.font = "600 11px 'JetBrains Mono', ui-monospace, monospace";
    const slabel = showStandard
      ? `ship (${shipStd.x.toFixed(2)}, ${shipStd.y.toFixed(2)})_std`
      : `ship`;
    ctx.fillText(slabel, shipPx.x + 10, shipPx.y + 16);

    // Origin marker.
    ctx.fillStyle = C_TEXT;
    ctx.beginPath();
    ctx.arc(origin.x, origin.y, 2.5, 0, Math.PI * 2);
    ctx.fill();
  }, [puzzle, shipStd, targetStd, isSolved, showStandard, toPx, domain]);

  useEffect(() => {
    draw();
  }, [draw]);

  return (
    <canvas
      ref={canvasRef}
      width={CANVAS_SIZE}
      height={CANVAS_SIZE}
      className="ct__canvas"
      role="img"
      aria-label="Coordinate translator canvas — ship navigating under custom-basis controls toward a target."
    />
  );
}

function drawArrow(
  ctx: CanvasRenderingContext2D,
  tail: Vec2,
  head: Vec2,
  color: string,
  label: string,
  width: number,
  dashed: boolean,
) {
  ctx.save();
  ctx.strokeStyle = color;
  ctx.fillStyle = color;
  ctx.lineWidth = width;
  if (dashed) ctx.setLineDash([6, 5]);
  ctx.beginPath();
  ctx.moveTo(tail.x, tail.y);
  ctx.lineTo(head.x, head.y);
  ctx.stroke();
  if (dashed) ctx.setLineDash([]);
  const dx = head.x - tail.x;
  const dy = head.y - tail.y;
  const len = Math.hypot(dx, dy);
  if (len > 5) {
    const ang = Math.atan2(dy, dx);
    const aLen = Math.min(10, len * 0.35);
    ctx.beginPath();
    ctx.moveTo(head.x, head.y);
    ctx.lineTo(
      head.x - aLen * Math.cos(ang - Math.PI / 6),
      head.y - aLen * Math.sin(ang - Math.PI / 6),
    );
    ctx.lineTo(
      head.x - aLen * Math.cos(ang + Math.PI / 6),
      head.y - aLen * Math.sin(ang + Math.PI / 6),
    );
    ctx.closePath();
    ctx.fill();
  }
  ctx.font = "700 13px 'JetBrains Mono', ui-monospace, monospace";
  ctx.textBaseline = "middle";
  ctx.fillText(label, head.x + 6, head.y - 8);
  ctx.restore();
}
