/**
 * GridMorphMatcher — reconstruct a tilted lattice from its picture.
 *
 * Used by:
 *   - linear-algebra-basis (this lesson)
 * Cross-link candidates:
 *   - linear-algebra-span (the lattice generated by integer combinations
 *     of u, v — visualised as the dot-grid)
 *   - linear-algebra-matrices (the basis matrix [u | v] is the matrix
 *     that takes the standard square grid to the displayed grid)
 *
 * THIS IS A REVERSE-ENGINEERING PUZZLE. The widget draws a target
 * lattice — a 2D grid of dots and gridlines tilted to some basis the
 * reader can't see. The reader drags two handles u and v on the same
 * canvas; the lattice they generate is drawn in real time over the
 * target. When the reader's lattice matches the target (every target
 * dot is within tolerance of a reader dot, and vice versa), the
 * widget flashes "solved".
 *
 * The pedagogical subtlety: the SAME lattice can be generated by many
 * different bases. {u, v} and {u + v, v} produce identical lattices.
 * More generally, {Au, Av} where A is any 2×2 integer matrix with
 * det A = ±1 (unimodular) is the same lattice. The widget accepts
 * ALL of them — there's no single "right answer" to memorise; the
 * reader can find any valid pair. This is the right pedagogy: a basis
 * is a coordinate ruleset, not a unique object, and multiple bases
 * describe the same coordinate-rule-set.
 *
 * Three difficulty puzzles:
 *   - Axis-aligned (standard basis) — warmup.
 *   - 30°-rotated — reader has to rotate u and v together.
 *   - Sheared — reader has to find non-orthogonal axes.
 *
 * Implements metaphor library §3 (deformation/morph — the standard
 * square grid being morphed to a tilted lattice) PLUS reverse-eng-
 * ineering as a new mechanic this codebase hasn't had at the basis
 * level.
 */

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { resolveColor, resolveColorAlpha } from "../../../lib/theme";
import { computeDomain, makeFromPx, makeToPx } from "../../../lib/geometry";
import { useWidgetTelemetry } from "../../../lib/telemetry";
import { WidgetExplainer } from "../shared/WidgetExplainer";
import "./GridMorphMatcher.css";

const CANVAS_SIZE = 380;
/** Hit tolerance: every TARGET dot in the lookup zone must have a
 * READER dot within MATCH_EPS of it (in math-coordinate units). */
const MATCH_EPS = 0.18;

interface Vec2 {
  x: number;
  y: number;
}

interface Puzzle {
  label: string;
  /** Target basis used to GENERATE the lattice the reader sees. The
   * reader's reconstruction need not equal this exactly — any
   * unimodular-equivalent basis is accepted. */
  targetU: Vec2;
  targetV: Vec2;
  description: string;
}

const PUZZLES: Puzzle[] = [
  {
    label: "Axis-aligned",
    targetU: { x: 1, y: 0 },
    targetV: { x: 0, y: 1 },
    description:
      "The standard basis. The lattice is the integer-coordinate grid.",
  },
  {
    label: "Rotated 30°",
    targetU: { x: Math.cos(Math.PI / 6), y: Math.sin(Math.PI / 6) },
    targetV: { x: -Math.sin(Math.PI / 6), y: Math.cos(Math.PI / 6) },
    description: "Orthonormal basis rotated 30° counter-clockwise.",
  },
  {
    label: "Sheared",
    targetU: { x: 1, y: 0 },
    targetV: { x: 0.6, y: 1 },
    description:
      "Non-orthogonal sheared basis — v points up-and-right. Multiple unimodular reconstructions exist.",
  },
  {
    label: "Stretched diagonal",
    targetU: { x: 1.2, y: 0.6 },
    targetV: { x: -0.4, y: 1.1 },
    description:
      "Generic basis — neither orthogonal nor unit. Reconstruct any equivalent pair.",
  },
];

interface GridMorphMatcherProps {
  onStateChange?: (state: Record<string, number>) => void;
}

export function GridMorphMatcher({ onStateChange }: GridMorphMatcherProps) {
  const { recordInteraction } = useWidgetTelemetry("GridMorphMatcher");
  const [puzzleIdx, setPuzzleIdx] = useState(0);
  const [u, setU] = useState<Vec2>({ x: 1.4, y: -0.3 });
  const [v, setV] = useState<Vec2>({ x: -0.3, y: 1.5 });
  const [showTarget, setShowTarget] = useState(true);

  const puzzle = PUZZLES[puzzleIdx];
  const targetU = puzzle.targetU;
  const targetV = puzzle.targetV;

  // Match check: every target lattice point in [-3, 3]^2 must have a
  // reader lattice point within MATCH_EPS — AND every reader lattice
  // point in that window must have a target point within MATCH_EPS.
  // (The bidirectional check rules out trivial degenerate readers like
  // u = v.)
  const match = useMemo(() => {
    const N = 3;
    let targetCovered = 0;
    let readerCovered = 0;
    let targetTotal = 0;
    let readerTotal = 0;

    const readerPoints: Vec2[] = [];
    const targetPoints: Vec2[] = [];
    for (let a = -N; a <= N; a++) {
      for (let b = -N; b <= N; b++) {
        readerPoints.push({ x: a * u.x + b * v.x, y: a * u.y + b * v.y });
        targetPoints.push({
          x: a * targetU.x + b * targetV.x,
          y: a * targetU.y + b * targetV.y,
        });
      }
    }
    // For each target lattice point inside the visible window, check if
    // SOME reader point is within eps.
    for (const t of targetPoints) {
      // Visible window check.
      if (Math.abs(t.x) > 2.6 || Math.abs(t.y) > 2.6) continue;
      targetTotal += 1;
      const ok = readerPoints.some(
        (r) => Math.hypot(r.x - t.x, r.y - t.y) < MATCH_EPS,
      );
      if (ok) targetCovered += 1;
    }
    for (const r of readerPoints) {
      if (Math.abs(r.x) > 2.6 || Math.abs(r.y) > 2.6) continue;
      readerTotal += 1;
      const ok = targetPoints.some(
        (t) => Math.hypot(t.x - r.x, t.y - r.y) < MATCH_EPS,
      );
      if (ok) readerCovered += 1;
    }
    return {
      forward: targetTotal === 0 ? 0 : targetCovered / targetTotal,
      backward: readerTotal === 0 ? 0 : readerCovered / readerTotal,
      total: Math.min(
        targetTotal === 0 ? 0 : targetCovered / targetTotal,
        readerTotal === 0 ? 0 : readerCovered / readerTotal,
      ),
    };
  }, [u, v, targetU, targetV]);

  const isSolved = match.total > 0.95;

  // Detect unimodular relation: if the reader's basis is a unimodular
  // combination of the target, surface that as an info message.
  const integerRel = useMemo(() => {
    // Solve [u | v] = [targetU | targetV] · K, where K is an integer matrix.
    // i.e. K = T⁻¹ · [u | v]. If K's entries are close to integers AND det K = ±1, unimodular.
    const D = targetU.x * targetV.y - targetU.y * targetV.x;
    if (Math.abs(D) < 0.001) return null;
    const Tinv00 = targetV.y / D;
    const Tinv01 = -targetV.x / D;
    const Tinv10 = -targetU.y / D;
    const Tinv11 = targetU.x / D;
    const k00 = Tinv00 * u.x + Tinv01 * u.y;
    const k10 = Tinv10 * u.x + Tinv11 * u.y;
    const k01 = Tinv00 * v.x + Tinv01 * v.y;
    const k11 = Tinv10 * v.x + Tinv11 * v.y;
    const roundClose = (x: number) => Math.abs(x - Math.round(x)) < 0.08;
    if (!roundClose(k00) || !roundClose(k10) || !roundClose(k01) || !roundClose(k11)) return null;
    const ri = Math.round(k00);
    const rj = Math.round(k10);
    const rk = Math.round(k01);
    const rl = Math.round(k11);
    const detK = ri * rl - rj * rk;
    if (Math.abs(detK) !== 1) return null;
    return {
      a: ri,
      b: rj,
      c: rk,
      d: rl,
      det: detK,
      identity: ri === 1 && rj === 0 && rk === 0 && rl === 1,
    };
  }, [u, v, targetU, targetV]);

  useEffect(() => {
    if (!onStateChange) return;
    onStateChange({
      puzzle_index: puzzleIdx,
      u_x: Number(u.x.toFixed(3)),
      u_y: Number(u.y.toFixed(3)),
      v_x: Number(v.x.toFixed(3)),
      v_y: Number(v.y.toFixed(3)),
      target_u_x: Number(targetU.x.toFixed(3)),
      target_u_y: Number(targetU.y.toFixed(3)),
      target_v_x: Number(targetV.x.toFixed(3)),
      target_v_y: Number(targetV.y.toFixed(3)),
      match_forward: Number(match.forward.toFixed(3)),
      match_backward: Number(match.backward.toFixed(3)),
      match_total: Number(match.total.toFixed(3)),
      solved: isSolved ? 1 : 0,
      unimodular: integerRel ? 1 : 0,
      unimodular_det: integerRel?.det ?? 0,
      identity_match: integerRel?.identity ? 1 : 0,
    });
  }, [
    puzzleIdx,
    u,
    v,
    targetU,
    targetV,
    match,
    isSolved,
    integerRel,
    onStateChange,
  ]);

  const choosePuzzle = useCallback(
    (idx: number) => {
      setPuzzleIdx(idx);
      // Restart from a "wrong" initial guess so the reader has work to do.
      setU({ x: 1.4, y: -0.3 });
      setV({ x: -0.3, y: 1.5 });
      recordInteraction("puzzle", { label: PUZZLES[idx].label });
    },
    [recordInteraction],
  );

  const reset = useCallback(() => {
    setU({ x: 1.4, y: -0.3 });
    setV({ x: -0.3, y: 1.5 });
    recordInteraction("reset");
  }, [recordInteraction]);

  const stateSummary = useMemo(() => {
    const uText = `u = (${u.x.toFixed(2)}, ${u.y.toFixed(2)})`;
    const vText = `v = (${v.x.toFixed(2)}, ${v.y.toFixed(2)})`;
    const targetText = `target generated by u_t = (${targetU.x.toFixed(2)}, ${targetU.y.toFixed(2)}), v_t = (${targetV.x.toFixed(2)}, ${targetV.y.toFixed(2)})`;
    const status = isSolved
      ? integerRel?.identity
        ? `SOLVED with the original target basis (K = identity).`
        : integerRel
          ? `SOLVED via a unimodular reconstruction K = [[${integerRel.a}, ${integerRel.c}], [${integerRel.b}, ${integerRel.d}]] (det ${integerRel.det}). Same lattice, different basis.`
          : `SOLVED (match score ${(match.total * 100).toFixed(0)}%).`
      : `Match ${(match.total * 100).toFixed(0)}% (forward ${(match.forward * 100).toFixed(0)}%, backward ${(match.backward * 100).toFixed(0)}%).`;
    return `Puzzle "${puzzle.label}": ${uText}; ${vText}; ${targetText}. ${status}`;
  }, [u, v, targetU, targetV, puzzle, match, isSolved, integerRel]);

  const stateKey = useMemo(
    () =>
      JSON.stringify({
        puzzle: puzzleIdx,
        u: [Number(u.x.toFixed(2)), Number(u.y.toFixed(2))],
        v: [Number(v.x.toFixed(2)), Number(v.y.toFixed(2))],
        solved: isSolved,
      }),
    [puzzleIdx, u, v, isSolved],
  );

  return (
    <div className={`gmm${isSolved ? " gmm--solved" : ""}`}>
      <header className="gmm__head">
        <div className="gmm__heading">
          <span className="gmm__heading-label">PUZZLE</span>
          <span className="gmm__heading-value">{puzzle.label}</span>
        </div>
        <div className="gmm__heading">
          <span className="gmm__heading-label">MATCH</span>
          <span
            className={`gmm__heading-value gmm__heading-value--${
              isSolved ? "ok" : match.total > 0.6 ? "warn" : "neutral"
            }`}
          >
            {(match.total * 100).toFixed(0)}%
          </span>
        </div>
        <div className="gmm__heading">
          <span className="gmm__heading-label">RECONSTRUCTION</span>
          <span className="gmm__heading-value">
            {integerRel
              ? integerRel.identity
                ? "K = identity"
                : `K = [[${integerRel.a}, ${integerRel.c}], [${integerRel.b}, ${integerRel.d}]] (det ${integerRel.det})`
              : "—"}
          </span>
        </div>
      </header>

      <MorphCanvas
        u={u}
        v={v}
        targetU={targetU}
        targetV={targetV}
        setU={setU}
        setV={setV}
        showTarget={showTarget}
        isSolved={isSolved}
      />

      <div
        className={`gmm__verdict gmm__verdict--${
          isSolved ? "solved" : match.total > 0.6 ? "close" : "working"
        }`}
      >
        <span className="gmm__verdict-label">Status</span>
        <span className="gmm__verdict-value">
          {isSolved
            ? integerRel?.identity
              ? `✓ Lattice matched with the original target basis.`
              : integerRel
                ? `✓ Lattice matched via a unimodular reconstruction (det K = ${integerRel.det}). Same coordinate-rule-set, different generators.`
                : `✓ Lattice matched.`
            : match.total > 0.6
              ? `Close — ${(match.total * 100).toFixed(0)}% match. Some target points still uncovered; tune u and v.`
              : `Match ${(match.total * 100).toFixed(0)}%. Drag the u and v handles until your gridlines align with the target dots.`}
        </span>
      </div>

      <div className="gmm__row">
        <button type="button" className="gmm__btn" onClick={reset}>
          Reset basis
        </button>
        <button
          type="button"
          className={`gmm__btn${showTarget ? " gmm__btn--on" : ""}`}
          onClick={() => {
            setShowTarget((s) => !s);
            recordInteraction("toggle_target", { on: !showTarget });
          }}
        >
          {showTarget ? "Hide target dots" : "Show target dots"}
        </button>
        <div className="gmm__puzzle-row">
          {PUZZLES.map((p, i) => (
            <button
              key={p.label}
              type="button"
              className={`gmm__puzzle-pick${i === puzzleIdx ? " gmm__puzzle-pick--active" : ""}`}
              onClick={() => choosePuzzle(i)}
            >
              {p.label}
            </button>
          ))}
        </div>
      </div>

      <WidgetExplainer
        widgetName="Grid morph matcher — reconstruct a lattice from its picture"
        widgetDescription="A reverse-engineering puzzle. The widget draws a target lattice — a tilted 2D grid of dots and gridlines generated by a hidden basis pair (u_t, v_t). The reader drags two handles u and v on the same canvas; their reader-lattice is drawn over the target in real time. Match score is computed bidirectionally: every target point in the visible window must have a reader point within tolerance, and vice versa. When match > 95%, the puzzle is solved. The key insight: lattice-equivalence is NOT basis-equivalence — multiple bases generate the same lattice, related by unimodular (integer, det = ±1) transformations. The widget computes the change-of-basis matrix K between the reader's basis and the target's, and surfaces whether K is identity or a non-trivial unimodular reconstruction. Three to four puzzles span: axis-aligned (standard basis), rotated 30°, sheared, and stretched diagonal."
        stateSummary={stateSummary}
        stateKey={stateKey}
      />
    </div>
  );
}

// ─── Canvas ────────────────────────────────────────────────────────────

interface MorphCanvasProps {
  u: Vec2;
  v: Vec2;
  targetU: Vec2;
  targetV: Vec2;
  setU: (v: Vec2) => void;
  setV: (v: Vec2) => void;
  showTarget: boolean;
  isSolved: boolean;
}

type DragHandle = "u" | "v" | null;

function MorphCanvas({
  u,
  v,
  targetU,
  targetV,
  setU,
  setV,
  showTarget,
  isSolved,
}: MorphCanvasProps) {
  const canvasRef = useRef<HTMLCanvasElement | null>(null);
  const [dragging, setDragging] = useState<DragHandle>(null);

  const domain = useMemo(
    () =>
      computeDomain(
        [
          u,
          v,
          targetU,
          targetV,
          { x: targetU.x * 2 + targetV.x * 2, y: targetU.y * 2 + targetV.y * 2 },
          { x: -2, y: -2 },
        ],
        { padding: 1.5, floor: 3, ceiling: 6 },
      ),
    [u, v, targetU, targetV],
  );

  const toPx = useMemo(() => makeToPx(CANVAS_SIZE, domain), [domain]);
  const fromPx = useMemo(() => makeFromPx(CANVAS_SIZE, domain), [domain]);

  const draw = useCallback(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;
    const ctx = canvas.getContext("2d");
    if (!ctx) return;
    const W = CANVAS_SIZE;
    const H = CANVAS_SIZE;
    ctx.clearRect(0, 0, W, H);

    const C_U = resolveColor("var(--widget-chart-1)");
    const C_V = resolveColor("var(--widget-chart-2)");
    const C_TARGET = resolveColor("var(--widget-chart-3)");
    const C_TEXT = resolveColor("var(--widget-text)");

    // Faint background standard grid.
    ctx.strokeStyle = "rgba(255, 255, 255, 0.04)";
    ctx.lineWidth = 1;
    const pxPerUnit = W / (2 * domain);
    const unitsPerHalf = Math.ceil(domain);
    for (let i = -unitsPerHalf; i <= unitsPerHalf; i++) {
      const xPx = W / 2 + i * pxPerUnit;
      const yPx = H / 2 - i * pxPerUnit;
      ctx.beginPath();
      ctx.moveTo(xPx, 0);
      ctx.lineTo(xPx, H);
      ctx.stroke();
      ctx.beginPath();
      ctx.moveTo(0, yPx);
      ctx.lineTo(W, yPx);
      ctx.stroke();
    }

    // TARGET lattice — drawn as dots, plus faint lines.
    const N = 3;
    if (showTarget) {
      // Target lines.
      ctx.strokeStyle = resolveColorAlpha("var(--widget-chart-3)", 0.18);
      ctx.lineWidth = 1.4;
      for (let i = -N; i <= N; i++) {
        const s = toPx({
          x: -N * targetU.x + i * targetV.x,
          y: -N * targetU.y + i * targetV.y,
        });
        const e = toPx({
          x: N * targetU.x + i * targetV.x,
          y: N * targetU.y + i * targetV.y,
        });
        ctx.beginPath();
        ctx.moveTo(s.x, s.y);
        ctx.lineTo(e.x, e.y);
        ctx.stroke();
      }
      for (let i = -N; i <= N; i++) {
        const s = toPx({
          x: -N * targetV.x + i * targetU.x,
          y: -N * targetV.y + i * targetU.y,
        });
        const e = toPx({
          x: N * targetV.x + i * targetU.x,
          y: N * targetV.y + i * targetU.y,
        });
        ctx.beginPath();
        ctx.moveTo(s.x, s.y);
        ctx.lineTo(e.x, e.y);
        ctx.stroke();
      }
      // Target dots.
      ctx.fillStyle = C_TARGET;
      for (let a = -N; a <= N; a++) {
        for (let b = -N; b <= N; b++) {
          const p = toPx({
            x: a * targetU.x + b * targetV.x,
            y: a * targetU.y + b * targetV.y,
          });
          if (p.x < -4 || p.x > W + 4 || p.y < -4 || p.y > H + 4) continue;
          ctx.beginPath();
          ctx.arc(p.x, p.y, 3.4, 0, Math.PI * 2);
          ctx.fill();
        }
      }
    }

    // READER lattice — gridlines + dots in basis colours.
    ctx.lineWidth = 1.6;
    ctx.strokeStyle = resolveColorAlpha("var(--widget-chart-1)", isSolved ? 0.55 : 0.35);
    for (let i = -N; i <= N; i++) {
      const s = toPx({
        x: -N * u.x + i * v.x,
        y: -N * u.y + i * v.y,
      });
      const e = toPx({
        x: N * u.x + i * v.x,
        y: N * u.y + i * v.y,
      });
      ctx.beginPath();
      ctx.moveTo(s.x, s.y);
      ctx.lineTo(e.x, e.y);
      ctx.stroke();
    }
    ctx.strokeStyle = resolveColorAlpha("var(--widget-chart-2)", isSolved ? 0.55 : 0.35);
    for (let i = -N; i <= N; i++) {
      const s = toPx({
        x: -N * v.x + i * u.x,
        y: -N * v.y + i * u.y,
      });
      const e = toPx({
        x: N * v.x + i * u.x,
        y: N * v.y + i * u.y,
      });
      ctx.beginPath();
      ctx.moveTo(s.x, s.y);
      ctx.lineTo(e.x, e.y);
      ctx.stroke();
    }
    // Reader dots — drawn as rings so target dots remain visible when matched.
    ctx.lineWidth = 1.5;
    ctx.strokeStyle = isSolved
      ? resolveColor("var(--widget-success)")
      : resolveColor("var(--widget-accent)");
    for (let a = -N; a <= N; a++) {
      for (let b = -N; b <= N; b++) {
        const p = toPx({ x: a * u.x + b * v.x, y: a * u.y + b * v.y });
        if (p.x < -4 || p.x > W + 4 || p.y < -4 || p.y > H + 4) continue;
        ctx.beginPath();
        ctx.arc(p.x, p.y, 5.5, 0, Math.PI * 2);
        ctx.stroke();
      }
    }

    // Basis vector arrows.
    const origin = toPx({ x: 0, y: 0 });
    drawArrow(ctx, origin, toPx(u), C_U, "u", 2.6);
    drawArrow(ctx, origin, toPx(v), C_V, "v", 2.6);

    // Handles.
    drawHandle(ctx, toPx(u), C_U);
    drawHandle(ctx, toPx(v), C_V);

    // Origin.
    ctx.fillStyle = C_TEXT;
    ctx.beginPath();
    ctx.arc(origin.x, origin.y, 2.5, 0, Math.PI * 2);
    ctx.fill();
  }, [u, v, targetU, targetV, showTarget, isSolved, toPx, domain]);

  useEffect(() => {
    draw();
  }, [draw]);

  useEffect(() => {
    const canvas = canvasRef.current;
    if (!canvas) return;

    const pointerMath = (e: PointerEvent): Vec2 => {
      const rect = canvas.getBoundingClientRect();
      const px = ((e.clientX - rect.left) / rect.width) * CANVAS_SIZE;
      const py = ((e.clientY - rect.top) / rect.height) * CANVAS_SIZE;
      return fromPx({ x: px, y: py });
    };

    const distance = (a: Vec2, b: Vec2) => Math.hypot(a.x - b.x, a.y - b.y);

    const onDown = (e: PointerEvent) => {
      const m = pointerMath(e);
      const hitRadius = 0.32;
      if (distance(m, u) < hitRadius) {
        setDragging("u");
        canvas.setPointerCapture(e.pointerId);
      } else if (distance(m, v) < hitRadius) {
        setDragging("v");
        canvas.setPointerCapture(e.pointerId);
      }
    };
    const onMove = (e: PointerEvent) => {
      if (!dragging) return;
      const m = pointerMath(e);
      const clamp = (n: number) =>
        Math.max(-domain + 0.1, Math.min(domain - 0.1, n));
      const vec = { x: clamp(m.x), y: clamp(m.y) };
      if (dragging === "u") setU(vec);
      else if (dragging === "v") setV(vec);
    };
    const onUp = (e: PointerEvent) => {
      if (canvas.hasPointerCapture(e.pointerId))
        canvas.releasePointerCapture(e.pointerId);
      setDragging(null);
    };

    canvas.addEventListener("pointerdown", onDown);
    canvas.addEventListener("pointermove", onMove);
    canvas.addEventListener("pointerup", onUp);
    canvas.addEventListener("pointercancel", onUp);
    return () => {
      canvas.removeEventListener("pointerdown", onDown);
      canvas.removeEventListener("pointermove", onMove);
      canvas.removeEventListener("pointerup", onUp);
      canvas.removeEventListener("pointercancel", onUp);
    };
  }, [dragging, u, v, domain, fromPx, setU, setV]);

  return (
    <canvas
      ref={canvasRef}
      width={CANVAS_SIZE}
      height={CANVAS_SIZE}
      className="gmm__canvas"
      role="img"
      aria-label="Grid morph matcher canvas — target lattice in chart-3 dots, reader's lattice in basis-colour rings."
    />
  );
}

function drawArrow(
  ctx: CanvasRenderingContext2D,
  tail: Vec2,
  head: Vec2,
  color: string,
  label: string,
  width: number,
) {
  ctx.save();
  ctx.strokeStyle = color;
  ctx.fillStyle = color;
  ctx.lineWidth = width;
  ctx.beginPath();
  ctx.moveTo(tail.x, tail.y);
  ctx.lineTo(head.x, head.y);
  ctx.stroke();
  const dx = head.x - tail.x;
  const dy = head.y - tail.y;
  const len = Math.hypot(dx, dy);
  if (len > 5) {
    const ang = Math.atan2(dy, dx);
    const aLen = Math.min(10, len * 0.32);
    ctx.beginPath();
    ctx.moveTo(head.x, head.y);
    ctx.lineTo(
      head.x - aLen * Math.cos(ang - Math.PI / 6),
      head.y - aLen * Math.sin(ang - Math.PI / 6),
    );
    ctx.lineTo(
      head.x - aLen * Math.cos(ang + Math.PI / 6),
      head.y - aLen * Math.sin(ang + Math.PI / 6),
    );
    ctx.closePath();
    ctx.fill();
  }
  ctx.font = "700 13px 'JetBrains Mono', ui-monospace, monospace";
  ctx.textBaseline = "middle";
  ctx.fillText(label, head.x + 6, head.y - 8);
  ctx.restore();
}

function drawHandle(ctx: CanvasRenderingContext2D, p: Vec2, color: string) {
  ctx.save();
  ctx.fillStyle = color;
  ctx.beginPath();
  ctx.arc(p.x, p.y, 7, 0, Math.PI * 2);
  ctx.fill();
  ctx.strokeStyle = "rgba(0, 0, 0, 0.6)";
  ctx.lineWidth = 1;
  ctx.stroke();
  ctx.restore();
}
