/**
 * Header harvester — scans every registered lesson's MDX and emits the H2/H3
 * section headers as link targets for the concept linker
 * (context/plans/authored-prose-autolinking.md). Two payoffs:
 *   1. an existing concept whose lesson has a matching header gets that header's
 *      anchor, so its links deep-link to the exact SECTION, not the lesson top;
 *   2. new header concepts (not already in `teaches`) become global link targets
 *      — "a matrix multiplication is a matrix multiplication regardless of domain".
 *
 * Anchors are produced with github-slugger, the same library rehype-slug uses to
 * id the headings, with one slugger per file advanced over EVERY heading (h1-h6)
 * in document order so the duplicate-suffix counter matches the rendered DOM ids.
 *
 * Generated output is src/lib/graph/headers.generated.ts — do not hand-edit.
 * Runs automatically as the first step of `pnpm build`; re-run manually with
 * `pnpm harvest-headers` after editing lesson headers.
 */
import GithubSlugger from "github-slugger";
import { readFileSync, writeFileSync } from "node:fs";
import { join } from "node:path";

const LESSONS_DIR = "src/lessons";
const META_FILE = "src/lib/graph/meta.ts";
const REGISTRY_FILE = "src/lessons/registry.ts";
const OUT = "src/lib/graph/headers.generated.ts";

// The slugs the concept graph knows about (top-level LESSON_META keys), so we
// harvest only real lessons.
const metaSrc = readFileSync(META_FILE, "utf8");
const slugSet = new Set(
  [...metaSrc.matchAll(/^ {2}(?:"([^"]+)"|([A-Za-z][\w-]*)):\s*\{/gm)].map((m) => m[1] || m[2]),
);

// slug → .mdx file, resolved through the registry (a slug's file name is NOT
// always its slug: `linear-algebra-foundations` lives in `linear-algebra.mdx`).
const registrySrc = readFileSync(REGISTRY_FILE, "utf8");
const importerToFile = {};
for (const m of registrySrc.matchAll(/const\s+(\w+)\s*=\s*\(\)\s*=>\s*import\("\.\/([^"]+\.mdx)"\)/g)) {
  importerToFile[m[1]] = m[2];
}
const slugToFile = {};
for (const m of registrySrc.matchAll(/slug:\s*"([^"]+)"[\s\S]*?Component:\s*lazy\((\w+)\)/g)) {
  const file = importerToFile[m[2]];
  if (file) slugToFile[m[1]] = file;
}

/** Strip inline markdown/math so the slug + phrase see plain text. */
function stripInline(s) {
  return s
    .replace(/\$[^$]*\$/g, " ") // inline math
    .replace(/`([^`]*)`/g, "$1") // inline code → its text
    .replace(/\*\*([^*]+)\*\*/g, "$1")
    .replace(/\*([^*]+)\*/g, "$1")
    .replace(/\[([^\]]+)\]\([^)]*\)/g, "$1") // link → label
    .replace(/\s+/g, " ")
    .trim();
}

const ARTICLE = /^(the|a|an)\s+/i;
/** The concept phrase: text before an em-dash/colon subtitle, minus a leading article. */
function toPhrase(clean) {
  return clean
    .split(/\s+[—–-]\s+|:\s+/)[0]
    .replace(ARTICLE, "")
    .trim();
}

const records = [];
for (const slug of slugSet) {
  const file = slugToFile[slug];
  if (!file) {
    console.warn(`  (no registry file for slug "${slug}" — skipped)`);
    continue;
  }
  const src = readFileSync(join(LESSONS_DIR, file), "utf8").replace(/```[\s\S]*?```/g, "");
  const slugger = new GithubSlugger();
  for (const line of src.split("\n")) {
    const m = /^(#{1,6})\s+(.+?)\s*$/.exec(line);
    if (!m) continue;
    const clean = stripInline(m[2]);
    if (!clean) continue;
    const anchor = slugger.slug(clean); // advance the counter for every heading
    const level = m[1].length;
    if (level < 2 || level > 3) continue; // but only emit H2/H3 as targets
    const phrase = toPhrase(clean);
    if (!phrase) continue;
    records.push({ slug, anchor, phrase, text: clean });
  }
}

const out = `/**
 * GENERATED by scripts/harvest-headers.mjs — do not edit by hand.
 * H2/H3 section headers harvested from every lesson's MDX, each with the
 * github-slugger anchor rehype-slug emits. Feeds the concept linker's target
 * index (src/lib/graph/targets.ts): existing concepts gain section anchors, new
 * header concepts become global targets. Re-run: pnpm harvest-headers.
 */
export interface HeaderRecord {
  /** Owning lesson slug. */
  slug: string;
  /** github-slugger anchor id of the heading (matches the rendered DOM id). */
  anchor: string;
  /** The concept phrase to match (pre-subtitle, article-stripped). */
  phrase: string;
  /** The full cleaned heading text (for reference / tooltips). */
  text: string;
}

export const HEADER_RECORDS: HeaderRecord[] = ${JSON.stringify(records, null, 2)};
`;

writeFileSync(OUT, out);
const lessons = new Set(records.map((r) => r.slug)).size;
console.log(`harvested ${records.length} headers from ${lessons} lessons → ${OUT}`);
